prompt PL/SQL Developer import file
prompt Created on 2012年5月1日 by Administrator
set feedback off
set define off
prompt Disabling triggers for SYS_MODELWIN...
alter table SYS_MODELWIN disable all triggers;
prompt Deleting SYS_MODELWIN...
delete from SYS_MODELWIN;
commit;
prompt Loading SYS_MODELWIN...
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (962, '小数点后长度设置', 'nfnumberlength.do?method=listPage', 'nfnumberlength', '小数点后长度设置', 1, 'admin', to_date('30-03-2012 16:33:48', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-03-2012 16:33:48', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsdhzdsz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (963, '收入项目', 'nfincomeitem.do?method=listPage', 'nfincomeitem', '收入项目', 21, 'GHZ', to_date('30-03-2012 17:27:07', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('30-03-2012 17:27:07', 'dd-mm-yyyy hh24:mi:ss'), 0, 'srxm');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (981, '录入凭证', 'enterVoucher.do?method=enterPage', 'nfentervoucher', '录入凭证', 1, 'admin', to_date('31-03-2012 11:16:19', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('31-03-2012 11:16:19', 'dd-mm-yyyy hh24:mi:ss'), 0, 'lrpz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1001, '银行存取款单', 'nfbankaccess.do?method=listPage', 'nfbankaccess', '银行存取款单', 21, 'GHZ', to_date('01-04-2012 09:41:37', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('01-04-2012 09:41:37', 'dd-mm-yyyy hh24:mi:ss'), 0, 'yxcqkd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1002, '凭证类型', 'nfvoucherclass.do?method=listPage', 'nfvoucherclass', '凭证类型', 21, 'GHZ', to_date('01-04-2012 13:29:37', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('05-04-2012 12:07:39', 'dd-mm-yyyy hh24:mi:ss'), 0, 'pzlx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1003, '付款单类型', 'nfpaymentclass.do?method=listPage', 'nfpaymentclass', '付款单类型', 21, 'GHZ', to_date('01-04-2012 15:23:26', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('01-04-2012 15:23:26', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fkdlx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1004, '收款单类型', 'nfproceedsclass.do?method=listPage', 'nfproceedsclass', '收款单类型', 21, 'GHZ', to_date('01-04-2012 15:24:22', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('01-04-2012 15:24:22', 'dd-mm-yyyy hh24:mi:ss'), 0, 'skdlx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1023, '凭证登帐', 'nfvouchertosubledger.do?method=listPage', 'nfvouchertosubledger', '凭证登帐', 21, 'GHZ', to_date('05-04-2012 16:05:46', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('05-04-2012 16:05:46', 'dd-mm-yyyy hh24:mi:ss'), 0, 'pzdz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (906, '企业信息', 'nfenterprise.do?method=listPage', 'nfenterprise', '企业信息', 1, 'admin', to_date('27-03-2012 16:45:35', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-04-2012 16:39:57', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qyxx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1021, '出纳总账', 'nfcashieraccount.do?method=listPage', 'nfcashieraccount', '出纳总账', 1, 'admin', to_date('05-04-2012 09:58:17', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('05-04-2012 09:58:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cnzz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1141, '制作凭证', 'makeVoucher.do?method=listPage', 'nfmakevoucher', '制作凭证', 21, 'GHZ', to_date('16-04-2012 14:17:43', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('16-04-2012 14:17:43', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zzpz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1041, '凭证编号规则', 'nfvouchercode.do?method=listPage', 'nfvouchercode', '凭证编号规则', 21, 'GHZ', to_date('06-04-2012 16:59:21', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('06-04-2012 17:04:14', 'dd-mm-yyyy hh24:mi:ss'), 0, 'pzbhgz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1061, '出纳会计对账', 'nfreconciliation.do?method=listPage', 'nfreconciliation', '出纳会计对账', 1, 'admin', to_date('09-04-2012 11:00:29', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('09-04-2012 11:00:29', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cnhjdz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1081, '科目余额初始化', 'nFInitialLegerController.do?method=listPage', 'nfinitialledger', '科目余额初始化', 1, 'admin', to_date('10-04-2012 09:44:06', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('10-04-2012 09:44:06', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kmyecsh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1082, '凭证登账', 'entryAccount.do?method=listPage', 'nfentryaccount', '凭证登账', 1, 'admin', to_date('10-04-2012 13:59:15', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('10-04-2012 13:59:15', 'dd-mm-yyyy hh24:mi:ss'), 0, 'pzdz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1101, '出纳余额初始化', 'nfinitcashier.do?method=listPage', 'nfinitcashier', '出纳余额初始化', 1, 'admin', to_date('11-04-2012 14:28:45', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-04-2012 14:28:45', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cnyecsh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1121, '附属物品完工单', 'prodsubsidiaryware.do?method=listPage', 'prodsubsidiaryware', '附属物品完工单', 1, 'admin', to_date('13-04-2012 12:16:36', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('13-04-2012 12:16:36', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fswpwgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1122, '科目明细账', 'nFSubLegerSearchPrintController.do?method=listPage', 'nfsublegersearchprint', '科目明细账', 1, 'admin', to_date('13-04-2012 13:05:27', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-04-2012 09:45:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kmmxz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1161, '发票类型', 'nfinvoiceclass.do?method=listPage', 'nfinvoiceclass', '发票类型', 21, 'GHZ', to_date('17-04-2012 12:07:13', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('17-04-2012 12:07:13', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fplx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1162, '财务报表', 'nfreportprint.do?method=listPage', 'nfreportprint', '财务报表', 21, 'GHZ', to_date('17-04-2012 14:21:13', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('17-04-2012 14:21:13', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cwbb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1163, '公共费用申请', 'commonmoneyuse.do?method=listPage', 'commonmoneyuse', '公共费用申请', 21, 'GHZ', to_date('17-04-2012 15:08:35', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('18-04-2012 14:25:30', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ggfysq');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1181, '报表内容设置', 'nfreportcontentset.do?method=listPage', 'nfreportcontentset', '报表内容设置', 21, 'GHZ', to_date('19-04-2012 10:59:30', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('19-04-2012 10:59:30', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bbnrsz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1201, '辅助核算账', 'nFCheckSubjectSearchPrintController.do?method=listPage', 'nfchecksubjectsearchprint', '辅助核算账', 1, 'admin', to_date('20-04-2012 13:15:58', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('20-04-2012 13:16:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fzhsz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (14, '单据审批类型', 'checkBusinessClassControl.do?method=listPage', 'syschecktype', '单据审批类型', 1, 'admin', to_date('04-07-2011 15:20:36', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 15:20:36', 'dd-mm-yyyy hh24:mi:ss'), 0, 'djsplx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (16, '模块设置', 'sysmodelwinsub.do?method=listPage', 'sysmodelwin', '模块设置', 1, 'admin', to_date('04-07-2011 13:41:29', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:41:29', 'dd-mm-yyyy hh24:mi:ss'), 0, 'mksz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (6, '物品信息与物品类别', 'baseWareClassAndWare.do?method=listPage', 'basewareclass', '物品信息与物品类别', 1, 'admin', to_date('04-07-2011 13:33:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:33:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wpxxywplb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (8, '物品单位与计量单位类别', 'baseWareUnitClassAndUnit.do?method=listPage', 'basewareunitclass', '物品单位与计量单位类别', 1, 'admin', to_date('04-07-2011 13:34:40', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:34:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wpdwyjldwlb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (11, '角色与权限', 'sysauthority.do?method=listPage', 'sysauthority', '角色与权限', 1, 'admin', to_date('04-07-2011 13:37:12', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:37:12', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jsyqx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (13, '操作员与类别', 'sysuserandclass.do?method=listPage', 'sysuserclass', '操作员与类别', 1, 'admin', to_date('04-07-2011 13:38:05', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:38:05', 'dd-mm-yyyy hh24:mi:ss'), 0, 'czyylb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (15, '单据审批流程', 'checkflow.do?method=listPage', 'syscheckflow', '单据审批流程', 1, 'admin', to_date('04-07-2011 15:21:01', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 15:21:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'djsplc');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (17, '模块与主窗口', 'sysformdefandmodel.do?method=listPage', 'sysformshow', '模块与主窗口', 1, 'admin', to_date('04-07-2011 13:41:55', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:41:55', 'dd-mm-yyyy hh24:mi:ss'), 0, 'mkyzck');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1, '库房库管', 'basestockclassmanage.do?method=listPage', 'basestock', '库房库管', 1, 'admin', to_date('04-07-2011 12:30:13', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 12:30:13', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kfkg');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (3, '计价方式类型', 'baseValuation.do?method=listPage', 'basevaluation', '计价方式类型', 1, 'admin', to_date('04-07-2011 12:30:34', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 12:30:34', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jjfslx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (4, '财务类别', 'baseFinanceClass.do?method=listPage', 'basefinance', '财务类别', 1, 'admin', to_date('04-07-2011 12:31:06', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 12:31:06', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cwlb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (2, '库房ABC分类', 'baseStockAbc.do?method=listPage', 'basestockabc', '库房ABC分类', 1, 'admin', to_date('04-07-2011 12:30:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 12:30:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kfABCfl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (83, '采购订单', 'buyScheduleSub.do?method=listPage', 'buyschedule', '采购订单', 1, 'admin', to_date('18-07-2011 15:44:21', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-07-2011 11:57:56', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgdd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (102, '采购报价', 'buyPrice.do?method=listPage', 'buyprice', '采购报价', 1, 'admin', to_date('19-07-2011 16:47:58', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-07-2011 16:47:58', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgbj');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (30, '销售订单', 'sellScheduleSub.do?method=listPage', 'sellschedule', '销售订单', 1, 'admin', to_date('07-07-2011 14:19:50', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:19:50', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsdd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (43, '质检项目', 'qualityItems.do?method=listPage', 'qualityitems', '质检项目', 1, 'admin', to_date('08-07-2011 16:54:11', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-07-2011 16:54:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zjxm');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (61, '交货方式', 'buyClientPortageModel.do?method=listPage', 'buyclientportagemodel', '交货方式', 1, 'admin', to_date('11-07-2011 16:36:15', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-07-2011 16:36:15', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jhfs');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (62, '供应商类别', 'buyClientType.do?method=listPage', 'buyclienttype', '供应商类别', 1, 'admin', to_date('11-07-2011 16:36:53', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-07-2011 16:36:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gyslb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (63, '供应商信息', 'buyClient.do?method=listPage', 'buyclient', '供应商信息', 1, 'admin', to_date('11-07-2011 16:37:32', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-07-2011 16:37:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gysxx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (81, '采购合同', 'buyContract.do?method=listPage', 'buycontract', '采购合同', 1, 'admin', to_date('18-07-2011 10:16:35', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('18-07-2011 10:16:35', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cght');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (104, '银行资料', 'nfbank.do?method=listPage', 'nfbank', '银行资料', 1, 'admin', to_date('19-07-2011 17:57:31', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-04-2012 16:36:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'yxzl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (105, '采购退货通知单', 'buybackwarenotificationsub.do?method=listPage', 'buybackwarenotification', '采购退货通知单', 1, 'admin', to_date('20-07-2011 12:51:50', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('20-07-2011 12:51:50', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgthtzd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (166, '车间', 'prodWorkShop.do?method=listPage', 'prodworkshop', '车间', 1, 'admin', to_date('22-07-2011 13:49:56', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-07-2011 13:49:56', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cj');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (168, '工种', 'prodWorkerClsee.do?method=listPage', 'prodworkerclass', '工种', 1, 'admin', to_date('22-07-2011 13:51:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-08-2011 11:33:14', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (38, '质检单', 'qualityExamineSub.do?method=listPage', 'qualityexamine', '质检单', 1, 'admin', to_date('21-07-2011 11:12:19', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-07-2011 11:12:19', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zjd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (121, '主生产计划', 'mPSContrller.do?method=listPage', 'prodMPS', '主生产计划', 1, 'admin', to_date('11-08-2011 17:57:37', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 17:57:37', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zscjh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (282, '部门设置', 'baseDept.do?method=listPage', 'basedept', '部门设置', 1, 'admin', to_date('15-08-2011 10:10:03', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-08-2011 12:07:08', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bmsz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (85, '生产工艺', 'prodCraftSub.do?method=listPage', 'prodcraft', '生产工艺', 1, 'admin', to_date('09-08-2011 13:28:14', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('09-08-2011 13:28:14', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scgy');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (284, '生产计划', 'prodPlanScheduleSubController.do?method=listPage', 'prodSchedule', '生产计划', 1, 'admin', to_date('15-08-2011 13:39:44', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-08-2011 13:39:44', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scjh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (64, '库存物品操作日志', 'stockWareOpreLog.do?method=listPage', 'stockwareoperlog', '库存物品操作日志', 1, 'admin', to_date('08-08-2011 14:35:58', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-08-2011 14:35:58', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kcwpczrz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (286, '岗位描述', 'humanPositionDes.do?method=listPage', 'humanpositiondes', '岗位描述', 1, 'admin', to_date('15-08-2011 15:34:11', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-08-2011 15:34:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gwms');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (87, '工厂日历', 'factoryCalendarController.do?method=listPage', 'prodfactoryCalendar', '工厂日历', 1, 'admin', to_date('09-08-2011 17:23:16', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('09-08-2011 17:23:16', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gcrl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (283, 'RCCP分析', 'rCCPController.do?method=listPage', 'prodRCCP', 'RCCP分析', 1, 'admin', to_date('14-08-2011 18:40:52', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('14-08-2011 18:40:52', 'dd-mm-yyyy hh24:mi:ss'), 0, 'RCCPfx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (285, '岗位设置', 'humanPosition.do?method=listPage', 'humanposition', '岗位设置', 1, 'admin', to_date('15-08-2011 13:49:52', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-08-2011 14:59:15', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gwsz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (290, '岗位工资', 'humanPositionPay.do?method=listPage', 'humanpositionpay', '岗位工资', 1, 'admin', to_date('16-08-2011 11:10:35', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-08-2011 11:10:35', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gwgz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (304, '岗位定员实施计划', 'humanImplemenContriver.do?method=listPage', 'humanimplemencontriver', '岗位定员实施计划', 1, 'admin', to_date('17-08-2011 11:31:41', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('17-08-2011 11:31:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gwdyssjh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (322, '工龄工资', 'humanSeniorityPay.do?method=listPage', 'humansenioritypay', '工龄工资', 1, 'admin', to_date('19-08-2011 14:35:19', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-08-2011 14:35:19', 'dd-mm-yyyy hh24:mi:ss'), 0, 'glgz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (342, '生产预测单', 'prodForecastSub.do?method=listPage', 'prodforecast', '生产预测单', 1, 'admin', to_date('22-08-2011 11:46:28', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 11:46:28', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scycd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (343, '替班记录', 'humanrelay.do?method=listPage', 'humanrelay', '替班记录', 1, 'admin', to_date('22-08-2011 12:08:36', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 12:08:36', 'dd-mm-yyyy hh24:mi:ss'), 0, 'tbjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (344, '调班记录', 'humanswap.do?method=listPage', 'humanswap', '调班记录', 1, 'admin', to_date('22-08-2011 14:49:38', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 14:49:38', 'dd-mm-yyyy hh24:mi:ss'), 0, 'dbjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (345, '工资方案', 'humanPayPrograms.do?method=listPage', 'humanpayprograms', '工资方案', 1, 'admin', to_date('22-08-2011 16:03:30', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 16:03:30', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzfa');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (288, '生产指令单计划', 'planScheduleMakeWareController.do?method=listPage', 'planScheduleMakeWare', '生产指令单计划', 1, 'admin', to_date('16-08-2011 09:50:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('17-08-2011 15:03:00', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczldjh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (289, '技能工资', 'humanCraftsmanShippay.do?method=listPage', 'humancraftsmanshippay', '技能工资', 1, 'admin', to_date('16-08-2011 10:32:12', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-08-2011 10:32:12', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jngz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (291, '员工信息', 'humanemployee.do?method=listPage', 'humanemployee', '员工信息', 1, 'admin', to_date('16-08-2011 14:32:28', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-08-2011 14:32:28', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ygxx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (305, '物料需求计划', 'planScheduleBuyWareController.do?method=listPage', 'planScheduleBuyWare', '物料需求计划', 1, 'admin', to_date('17-08-2011 14:39:02', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('17-08-2011 15:02:43', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wlxqjh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (361, '维修记录', 'humanrepair.do?method=listPage', 'humanrepair', '维修记录', 1, 'admin', to_date('23-08-2011 09:18:02', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-08-2011 09:18:02', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wxjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (381, '车间库房', 'prodWorkShopStock.do?method=workShopListPage', 'prodworkshopstock', '车间库房', 1, 'admin', to_date('24-08-2011 10:18:45', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-08-2011 18:08:52', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cjkf');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (382, '班组领料类型', 'prodWorkWareClass.do?method=listPage', 'prodworkwareclass', '班组领料类型', 1, 'admin', to_date('24-08-2011 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-08-2011 13:28:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bzlllx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (49, '车间退料单', 'prodBackWareSub.do?method=listPage', 'prodbackware', '车间退料单', 1, 'admin', to_date('24-08-2011 14:02:44', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-08-2011 15:20:50', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cjtld');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (89, '班组领料', 'prodAcquireWareSubController.do?method=listPage', 'prodWorkAcquireWare', '班组领料', 1, 'admin', to_date('26-08-2011 10:26:20', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-09-2011 15:57:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bzll');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (90, '生产加工单', 'prodWorkMake.do?method=listPage', 'prodworkmake', '生产加工单', 1, 'admin', to_date('26-08-2011 11:25:31', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('26-08-2011 11:42:26', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scjgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (401, '班组交接单', 'prodWorkSwapSub.do?method=listPage', 'prodworkswap', '班组交接单', 1, 'admin', to_date('28-08-2011 15:23:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('28-08-2011 15:23:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bzjjd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (441, '工资记录', 'humanpay.do?method=listPage', 'humanpay', '工资记录', 1, 'admin', to_date('30-08-2011 12:11:01', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-08-2011 12:11:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (461, '工资历史记录', 'humanpayhistory.do?method=listPage', 'humanpayhistory', '工资历史记录', 1, 'admin', to_date('01-09-2011 09:49:40', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-09-2011 09:49:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzlsjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (465, '经销商销售台账', 'selldealeraccounts.do?method=listPage', 'selldealeraccounts', '经销商销售台账', 1, 'admin', to_date('05-09-2011 16:42:47', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('05-09-2011 16:42:47', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jxsxstz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (466, '供应商采购台账', 'buysupplieraccounts.do?method=listPage', 'buysupplieraccounts', '供应商采购台账', 1, 'admin', to_date('05-09-2011 17:35:13', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('05-09-2011 17:35:13', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gyscgtz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (462, '生产计划完成情况', 'prodInformationSearchController.do?method=prodPlanScheduleInfoPage', 'prodPlanScheduleInfoPage', '生产计划完成情况', 1, 'admin', to_date('02-09-2011 11:16:28', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('02-09-2011 11:16:28', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scjhwcqk');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (484, '物品销售及生产情况', 'pictureSearch.do?method=sellProdPicture', 'prodSellWarePicture', '物品销售及生产情况', 1, 'admin', to_date('06-09-2011 16:25:54', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-09-2011 16:25:54', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wpxsjscqk');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (504, '销售额情况', 'pictureSearch.do?method=sellAmountOfMoneyPicture', 'sellAmountOfMoneyData', '销售额情况', 1, 'admin', to_date('07-09-2011 11:23:42', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-09-2011 11:23:42', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xseqk');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (521, '修改密码', 'sysAuthorityData.do?method=passwordPage', 'syspassword', '修改密码', 1, 'admin', to_date('13-09-2011 15:56:40', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('13-09-2011 15:56:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xgmm');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (561, '销售不良记录', 'sellBadRecord.do?method=listPage', 'sell_badrecord', '销售不良记录', 1, 'admin', to_date('16-10-2011 20:00:09', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-10-2011 20:00:09', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsbljl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (603, '主生产指令', 'prodMainCommand.do?method=listPage', 'prodMainCommand', '主生产指令', 1, 'admin', to_date('23-10-2011 21:38:01', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-10-2011 21:38:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zsczl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (601, '销售发货信息', 'sellsendmark.do?method=listPage', 'sellsendmark', '销售发货信息', 1, 'admin', to_date('23-10-2011 19:59:43', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-10-2011 19:59:43', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsfhxx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (602, '办公室发货指令', 'sellsendwarecommandofsub.do?method=listPage', 'sellsendwarecommandof', '办公室发货指令', 1, 'admin', to_date('23-10-2011 20:02:07', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-10-2011 20:02:07', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bgsfhzl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (621, '业务单据查询', 'businessdocumentsquery.do?method=listPage', 'businessdocumentsquery', '业务单据查询', 1, 'admin', to_date('05-12-2011 14:37:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('05-12-2011 14:37:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ywdjcx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (581, '待检库现有库存', 'stockWareStockChecking.do?method=listPage', 'stockcheckingsuball', '待检库现有库存', 1, 'admin', to_date('23-10-2011 15:38:57', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-10-2011 15:38:57', 'dd-mm-yyyy hh24:mi:ss'), 0, 'djkxykc');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (541, '请假方案', 'humanLeavePrograms.do?method=listPage', 'humanleaveprograms', '请假方案', 1, 'admin', to_date('14-10-2011 17:43:49', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('14-10-2011 17:43:49', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qjfa');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (542, '请假记录', 'humanleave.do?method=listPage', 'humanleave', '请假记录', 1, 'admin', to_date('14-10-2011 18:09:50', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('14-10-2011 18:09:50', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qjjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (463, '生产指令完成情况', 'prodInformationSearchController.do?method=prodCommandInfoPage', 'prodCommandInfoPage', '生产指令完成情况', 1, 'admin', to_date('02-09-2011 13:20:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('02-09-2011 13:20:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlwcqk');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (464, '车间领料情况', 'prodInformationSearchController.do?method=prodWorkShopAcquireWareInfoPage', 'prodWorkShopAquireWaeInfoPage', '车间领料情况', 1, 'admin', to_date('05-09-2011 10:31:58', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('05-09-2011 10:31:58', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cjllqk');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (294, '档案信息', 'humanDossierInfoSub.do?method=listPage', 'humandossierinfo', '档案信息', 1, 'admin', to_date('16-08-2011 14:49:48', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-08-2011 14:49:48', 'dd-mm-yyyy hh24:mi:ss'), 0, 'daxx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (301, '工作岗位评价', 'humanPositionRation.do?method=listPage', 'humanpositionration', '工作岗位评价', 1, 'admin', to_date('17-08-2011 09:53:09', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('17-08-2011 09:53:09', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzgwpj');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1202, '资产状态', 'financialassetsstatus.do?method=listPage', 'nfassetsstatus', '资产状态', 1, 'admin', to_date('24-04-2012 14:08:30', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-04-2012 14:08:30', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zczt');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1203, '固定资产', 'financialassetsdetail.do?method=listPage', 'nfassetsdetail', '固定资产', 1, 'admin', to_date('24-04-2012 14:10:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-04-2012 14:10:08', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gdzc');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1222, '财务报表(JS)', 'nfreportprint_js.do?method=listPage', 'nfreportprint_js', '财务报表(JS)', 1, 'admin', to_date('26-04-2012 17:00:26', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('26-04-2012 17:00:26', 'dd-mm-yyyy hh24:mi:ss'), 1, 'cwbb(JS)');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1242, '打印凭证', 'printVoucher.do?method=printPage', 'nfprintvoucher', '打印凭证', 1, 'admin', to_date('27-04-2012 12:25:12', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('27-04-2012 12:25:12', 'dd-mm-yyyy hh24:mi:ss'), 0, 'dypz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (302, '岗位定员计划', 'humanContriver.do?method=listPage', 'humancontriver', '岗位定员计划', 1, 'admin', to_date('17-08-2011 10:56:16', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('17-08-2011 10:56:16', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gwdyjh');
commit;
prompt 100 records committed...
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (306, '员工培训', 'humanTrainingSub.do?method=listPage', 'humantraining', '员工培训', 1, 'admin', to_date('17-08-2011 17:37:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('17-08-2011 17:37:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ygpx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (341, '生产指令', 'prodCommandController.do?method=listPage', 'prodCommand', '生产指令', 1, 'admin', to_date('22-08-2011 09:20:55', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 09:20:55', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (346, '维修方案', 'humanRepairPrograms.do?method=listPage', 'humanrepairprograms', '维修方案', 1, 'admin', to_date('22-08-2011 17:30:21', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 17:30:21', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wxfa');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (383, '车间领料单', 'prodAcquireWareSubController.do?method=listPage', 'prodAcquireWare', '车间领料单', 1, 'admin', to_date('24-08-2011 10:48:02', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-09-2011 15:55:02', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cjlld');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (384, '车间领料类型', 'prodAcquireWareClass.do?method=listPage', 'prodacquirewareclass', '车间领料类型', 1, 'admin', to_date('24-08-2011 10:49:16', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-08-2011 13:28:20', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cjlllx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (421, '班组退料', 'prodWorkBackWareSubController.do?method=listPage', 'prodWorkBackWare', '班组退料', 1, 'admin', to_date('29-08-2011 09:40:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-09-2011 15:56:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bztl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (292, '住房管理', 'humanHouseuserInfo.do?method=listPage', 'humanhouseinfo', '住房管理', 1, 'admin', to_date('16-08-2011 14:49:14', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-08-2011 17:40:22', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zfgl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (293, '员工招聘', 'humanwantadSub.do?method=listPage', 'humanwantad', '员工招聘', 1, 'admin', to_date('16-08-2011 14:49:32', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('16-08-2011 14:49:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ygzp');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (68, '生产完工单', 'prodFinishedWare.do?method=listPage', 'profinishedware', '生产完工单', 1, 'admin', to_date('25-08-2011 09:43:59', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('25-08-2011 09:43:59', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scwgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (69, '生产派工单', 'prodStartWorking.do?method=listPage', 'prodstartworking', '生产派工单', 1, 'admin', to_date('25-08-2011 12:07:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('25-08-2011 12:07:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scpgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (146, '采购运费发票', 'buyportage.do?method=listPage', 'buyportage', '采购运费发票', 1, 'admin', to_date('21-07-2011 17:14:22', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-07-2011 17:57:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgyffp');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (20, '采购到货通知单', 'buyComeWareNotIficationSub.do?method=listPage', 'buycomewarenotification', '采购到货通知单', 1, 'admin', to_date('20-07-2011 12:37:50', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-07-2011 14:29:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgdhtzd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (169, '库房仓位', 'stockPosition.do?method=listPage', 'stockposition', '库房仓位', 1, 'admin', to_date('22-07-2011 17:07:36', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-07-2011 17:07:36', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kfcw');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (108, '出库单类型', 'stockOutStockClass.do?method=listPage', 'stockoutstockclass', '出库单类型', 1, 'admin', to_date('20-07-2011 17:09:21', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('20-07-2011 17:09:21', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ckdlx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (125, '客户奖励', 'sellClientReward.do?method=listPage', 'sellclientreward', '客户奖励', 1, 'admin', to_date('21-07-2011 09:43:54', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-07-2011 16:04:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'khjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (218, '出库单', 'stockoutstocksub.do?method=listPage', 'stockoutstock', '出库单', 1, 'admin', to_date('26-07-2011 15:32:51', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-08-2011 10:26:48', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ckd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (219, 'BOM物品替换', 'prodBOMWarereplace.do?method=listPage', 'prodbomwarereplace', 'BOM物品替换', 1, 'admin', to_date('27-07-2011 11:56:44', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('27-07-2011 11:56:44', 'dd-mm-yyyy hh24:mi:ss'), 0, 'BOMwpth');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (239, '物品BOM', 'prodWareBOMSub.do?method=listPage', 'prodwarebom', '物品BOM', 1, 'admin', to_date('29-07-2011 17:12:04', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('29-07-2011 17:12:04', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wpBOM');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (242, '入库单', 'stockInStockSub.do?method=listPage', 'stockinstock', '入库单', 1, 'admin', to_date('01-08-2011 10:28:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('09-08-2011 17:35:56', 'dd-mm-yyyy hh24:mi:ss'), 0, 'rkd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (243, '生产工序', 'prodWorkProcess.do?method=listPage', 'prodwareprocess', '生产工序', 1, 'admin', to_date('01-08-2011 10:53:42', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-08-2011 10:53:42', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scgx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (244, '班组', 'prodWorkGroupSub.do?method=listPage', 'prodwaregroup', '班组', 1, 'admin', to_date('01-08-2011 13:21:12', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-08-2011 13:23:15', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (245, '库房现有库存', 'stockWareStocking.do?method=listPage', 'stockwarestocking', '库房现有库存', 1, 'admin', to_date('01-08-2011 17:58:38', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-08-2011 17:58:38', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kfxykc');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (262, '班制', 'prodWorkTimeModalSub.do?method=listPage', 'prodworktimemodal', '班制', 1, 'admin', to_date('02-08-2011 12:32:56', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('02-08-2011 12:32:56', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (48, '返工领料查询', 'prodreversewareinfo.do?method=listPage', 'prodreversewareinfo', '返工领料查询', 5, '历闯', to_date('19-03-2012 11:33:11', 'dd-mm-yyyy hh24:mi:ss'), 5, '历闯', to_date('19-03-2012 11:33:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fgllcx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (867, '生产完工情况及成品率查询', 'prodfinishednum.do?method=listPage', 'prodfinishednum', '生产完工情况及成品率查询', 3, '王利', to_date('19-03-2012 11:58:00', 'dd-mm-yyyy hh24:mi:ss'), 3, '王利', to_date('19-03-2012 11:58:00', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scwgqkjcplcx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (866, '供应商到货合格率情况', 'qualityqualifiedrate.do?method=listPage', 'qualityqualifiedrate', '供应商到货合格率情况', 1, 'admin', to_date('19-03-2012 11:46:50', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-03-2012 11:46:50', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gysdhhglqk');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (885, '全局配置', 'environment.do?method=listPage', 'environment', '全局配置', 41, '程荣昌', to_date('26-03-2012 11:08:21', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('27-03-2012 12:13:45', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qjpz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (18, '生产用料查询', 'prodworkwareuse.do?method=listPage', 'prodworkwareuse', '生产用料查询', 5, '历闯', to_date('19-03-2012 11:31:08', 'dd-mm-yyyy hh24:mi:ss'), 5, '历闯', to_date('19-03-2012 11:31:08', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scylcx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (865, '采购物品平均价查询', 'buycomewareavg.do?method=listPage', 'buycomewareavg', '采购物品平均价查询', 1, 'admin', to_date('19-03-2012 11:46:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-03-2012 11:46:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgwppjjcx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (261, '工作中心', 'prodWorkCenter.do?method=listPage', 'prodworkcenter', '工作中心', 1, 'admin', to_date('02-08-2011 10:30:30', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('02-08-2011 10:30:30', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzzx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (221, '库存调拨单', 'stockTransferSub.do?method=listPage', 'stocktransfer', '库存调拨单', 1, 'admin', to_date('27-07-2011 15:09:51', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-08-2011 10:26:30', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kcdbd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (107, '入库单类型', 'stockInStockClass.do?method=listPage', 'stockinstockclass', '入库单类型', 1, 'admin', to_date('20-07-2011 16:29:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('20-07-2011 16:29:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'rkdlx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (109, '库存调拨单类型', 'stockTransferClass.do?method=listPage', 'stocktransferclass', '库存调拨单类型', 1, 'admin', to_date('20-07-2011 17:14:55', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-09-2011 15:44:52', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kcdbdlx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (19, '单据审批', 'checkOperationFormControl.do?method=listPage', 'syscheckoperation', '单据审批', 1, 'admin', to_date('06-07-2011 17:36:57', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-07-2011 17:36:57', 'dd-mm-yyyy hh24:mi:ss'), 0, 'djsp');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (101, '请验单', 'qualityForwardExamineSub.do?method=listPage', 'qualityforwardexamine', '请验单', 1, 'admin', to_date('19-07-2011 09:17:15', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-07-2011 09:17:15', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qyd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (21, '税率设置', 'nfrate.do?method=listPage', 'nfrate', '税率设置', 1, 'admin', to_date('07-07-2011 13:46:59', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('29-03-2012 17:11:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 'slsz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (23, '销售客户组别', 'sellClientGroup.do?method=listPage', 'sellclientgroup', '销售客户组别', 1, 'admin', to_date('07-07-2011 14:35:41', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:35:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xskhzb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (24, '销售客户合作等级', 'sellClientLevel.do?method=listPage', 'sellclientlevel', '销售客户合作等级', 1, 'admin', to_date('07-07-2011 14:13:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:13:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xskhhzdj');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (25, '销售客户类型', 'sellClientType.do?method=listPage', 'sellclienttype', '销售客户类型', 1, 'admin', to_date('07-07-2011 14:14:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:14:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xskhlx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (26, '客户运费结算方式', 'sellUserPortageModel.do?method=listPage', 'selluserportagemodel', '客户运费结算方式', 1, 'admin', to_date('07-07-2011 14:14:57', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:14:57', 'dd-mm-yyyy hh24:mi:ss'), 0, 'khyfjsfs');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (27, '销售客户', 'sellclient.do?method=listPage', 'sellclient', '销售客户', 1, 'admin', to_date('07-07-2011 14:17:43', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:17:43', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xskh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (28, '销售合同', 'sellContract.do?method=listPage', 'sellcontract', '销售合同', 1, 'admin', to_date('07-07-2011 14:18:53', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:18:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsht');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (29, '年销售计划', 'sellPlanAndSubPlan.do?method=listPage', 'sellplan', '年销售计划', 1, 'admin', to_date('07-07-2011 14:19:29', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:19:29', 'dd-mm-yyyy hh24:mi:ss'), 0, 'nxsjh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (31, '商品价格维护', 'sellPrice.do?method=listPage', 'sellprice', '商品价格维护', 1, 'admin', to_date('07-07-2011 14:20:32', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:20:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'spjgwh');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (32, '商品报价', 'sellQuotedPriceSub.do?method=listPage', 'sellquotedprice', '商品报价', 1, 'admin', to_date('07-07-2011 14:22:32', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:22:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'spbj');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (33, '销售发货指令', 'sellsendwarecommandsub.do?method=listPage', 'sellsendwarecommand', '销售发货指令', 1, 'admin', to_date('07-07-2011 14:23:19', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:23:19', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsfhzl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (34, '销售到货通知单', 'sellWareNotificationSub.do?method=listPage', 'sellwarenotification', '到货通知单', 1, 'admin', to_date('07-07-2011 14:24:33', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 11:06:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsdhtzd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (35, '销售发票申请', 'sellInvoiceSub.do?method=listPage', 'sellinvoice', '销售发票申请', 1, 'admin', to_date('07-07-2011 14:25:12', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:25:12', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsfpsq');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (36, '销售运费', 'sellPortageAndPortageSub.do?method=listPage', 'sellportage', '销售运费', 1, 'admin', to_date('07-07-2011 14:25:56', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:25:56', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsyf');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (37, '销售退货', 'sellbackwaresub.do?method=listPage', 'sellbackware', '销售退货', 1, 'admin', to_date('07-07-2011 14:26:30', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:26:30', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsth');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (41, '质检结果', 'qualityResult.do?method=listPage', 'qualityresult', '质检结果', 1, 'admin', to_date('08-07-2011 16:37:41', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-07-2011 16:37:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zjjg');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (822, '生产再利用回收单', 'prodreusewaresub.do?method=listPage', 'prodreuseware', '生产再利用回收单', 1, 'admin', to_date('08-03-2012 09:50:53', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-03-2012 09:50:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlyhsd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (823, '生产再利用生产指令', 'prodreusecommand.do?method=listPage', 'prodreusecommand', '生产再利用生产指令', 1, 'admin', to_date('08-03-2012 10:59:43', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-03-2012 11:08:14', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlysczl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (825, '生产再利用完工单', 'prodreusefinishedware.do?method=listPage', 'prodreusefinishedware', '生产再利用完工单', 1, 'admin', to_date('08-03-2012 11:10:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-03-2012 11:10:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlywgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (842, '返工完工单', 'prodreversefinishedware.do?method=listPage', 'prodreversefinishedware', '返工完工单', 1, 'admin', to_date('09-03-2012 10:48:07', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('09-03-2012 10:48:07', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fgwgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (843, '返工领料单', 'prodreverseacquirewaresub.do?method=listPage', 'prodreverseacquireware', '返工领料单', 1, 'admin', to_date('09-03-2012 11:04:07', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('09-03-2012 11:28:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fglld');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (864, '保留样品档案', 'qualityrssearch.do?method=listPage', 'qualityrssearch', '保留样品档案', 1, 'admin', to_date('15-03-2012 13:34:46', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-03-2012 13:35:06', 'dd-mm-yyyy hh24:mi:ss'), 0, 'blypda');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (802, '返工生产指令单', 'prodreversecommand.do?method=listPage', 'prodreversecommand', '返工生产指令单', 1, 'admin', to_date('07-03-2012 16:18:14', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-03-2012 16:18:14', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fgsczld');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (824, '生产再利用领料单', 'prodreuseacquirewaresub.do?method=listPage', 'prodreuseacquireware', '生产再利用领料单', 1, 'admin', to_date('08-03-2012 11:09:06', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-03-2012 11:09:06', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlylld');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (42, '质检员', 'qualityOperator.do?method=listPage', 'qualityoperator', '质检员', 1, 'admin', to_date('08-07-2011 16:53:49', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-07-2011 16:53:49', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zjy');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (642, '工作中心清场单', 'prodclearingsub.do?method=listPage', 'prodclearing', '工作中心清场单', 1, 'admin', to_date('30-01-2012 16:10:51', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:10:51', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzzxqcd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (645, '润滑单', 'equipoilingsub.do?method=listPage', 'equipoiling', '润滑单', 1, 'admin', to_date('30-01-2012 16:52:06', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:52:06', 'dd-mm-yyyy hh24:mi:ss'), 0, 'rhd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (647, '故障登记单', 'equipStopPageSub.do?method=listPage', 'equipstoppage', '故障登记单', 1, 'admin', to_date('30-01-2012 16:57:11', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:57:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzdjd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (658, '蒸汽锅炉及附属设备运行记录', 'boilerequiprun.do?method=listPage', 'boilerequiprun', '蒸汽锅炉及附属设备运行记录', 1, 'admin', to_date('30-01-2012 17:22:29', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:22:29', 'dd-mm-yyyy hh24:mi:ss'), 1, 'zqgljfssbyxjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (641, '不合格物品入库单', 'stockFailedWareSub.do?method=listPage', 'stockfailedware', '不合格物品入库单', 1, 'admin', to_date('30-01-2012 15:46:42', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-03-2012 16:38:21', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bhgwprkd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (649, '保养计划单', 'equipKeepPlan.do?method=listPage', 'equipkeepplan', '保养计划单', 1, 'admin', to_date('30-01-2012 17:01:22', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:01:22', 'dd-mm-yyyy hh24:mi:ss'), 0, 'byjhd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (653, '维修单', 'equipRepairSub.do?method=listPage', 'equiprepair', '维修单', 1, 'admin', to_date('30-01-2012 17:04:49', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:04:49', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wxd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (655, '保养单', 'equipKeepSub.do?method=listPage', 'equipkeep', '保养单', 1, 'admin', to_date('30-01-2012 17:09:07', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:09:07', 'dd-mm-yyyy hh24:mi:ss'), 0, 'byd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (656, '安装单', 'equipSetupSub.do?method=listPage', 'equipsetup', '安装单', 1, 'admin', to_date('30-01-2012 17:09:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:09:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'azd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (657, '变更单', 'equipChangeSub.do?method=listPage', 'equipchange', '变更单', 1, 'admin', to_date('30-01-2012 17:11:51', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:11:51', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (701, '保留样品录入单', 'qualityRetentionSam.do?method=listPage', 'qualityretentionsam', '保留样品录入单', 1, 'admin', to_date('21-02-2012 11:35:02', 'dd-mm-yyyy hh24:mi:ss'), 7, '刘雨', to_date('15-03-2012 13:34:35', 'dd-mm-yyyy hh24:mi:ss'), 0, 'blyplrd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (741, '生产环境检测单', 'prodenvironmenttestsub.do?method=listPage', 'prodenvironmenttest', '生产环境检测单', 1, 'admin', to_date('22-02-2012 09:45:37', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-02-2012 09:45:37', 'dd-mm-yyyy hh24:mi:ss'), 0, 'schjjcd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (761, '保留样品检测单', 'qualityretentionsamtestSub.do?method=listPage', 'qualityretentionsamtest', '保留样品检测单', 1, 'admin', to_date('23-02-2012 11:01:22', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-02-2012 11:02:02', 'dd-mm-yyyy hh24:mi:ss'), 0, 'blypjcd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (721, '制水检测单', 'prodwatertestsub.do?method=listPage', 'prodwatertest', '制水检测单', 1, 'admin', to_date('21-02-2012 14:27:53', 'dd-mm-yyyy hh24:mi:ss'), 5, '历闯', to_date('19-03-2012 14:49:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zsjcd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (743, '保留样品检测计划单', 'qualityretentionsamplanSub.do?method=listPage', 'qualityretentionsamplan', '保留样品检测计划单', 1, 'admin', to_date('22-02-2012 12:16:09', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-02-2012 13:21:28', 'dd-mm-yyyy hh24:mi:ss'), 0, 'blypjcjhd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (762, '物品报价比较', 'buypriceompare.do?method=listPage', 'buypricecompare', '物品报价比较', 1, 'admin', to_date('23-02-2012 15:28:00', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-02-2012 15:28:00', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wpbjbj');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (781, '计划执行方案', 'sysPlanProgram.do?method=listPage', 'sysplanprogram', '计划执行方案', 1, 'admin', to_date('24-02-2012 09:40:35', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-02-2012 09:40:35', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jhzxfa');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (801, '供应商预付款申请单', 'buypayapply.do?method=listPage', 'buypayapply', '供应商预付款申请单', 1, 'admin', to_date('06-03-2012 15:58:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-03-2012 15:58:08', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gysyfksqd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (659, '锅炉交接班记录', 'boilerequiphand.do?method=listPage', 'boilerequiphand', '锅炉交接班记录', 1, 'admin', to_date('30-01-2012 17:27:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:27:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 'gljjbjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (660, '水处理设备运行及水质化验记录', 'boilerwatertreatment.do?method=listPage', 'boilerwatertreatment', '水处理设备运行及水质化验记录', 1, 'admin', to_date('30-01-2012 17:28:19', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:28:19', 'dd-mm-yyyy hh24:mi:ss'), 1, 'sclsbyxjszhyjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (661, '设备保养类别', 'equipKeepClass.do?method=listPage', 'equipkeepclass', '设备保养类别', 1, 'admin', to_date('30-01-2012 17:40:34', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:40:34', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sbbylb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (643, '设备档案', 'equipArchives.do?method=listPage', 'equipArchives', '设备档案', 1, 'admin', to_date('30-01-2012 16:50:29', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:50:29', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sbda');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (644, '检测计划单', 'equipExaminePlanSub.do?method=listPage', 'equipexamineplan', '检测计划单', 1, 'admin', to_date('30-01-2012 16:51:12', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:51:12', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jcjhd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (646, '检测单', 'equipExamineSub.do?method=listPage', 'equipexamine', '检测单', 1, 'admin', to_date('30-01-2012 16:54:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:54:08', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jcd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (648, '请修单', 'equipRequestSub.do?method=listPage', 'equiprequest', '请修单', 1, 'admin', to_date('30-01-2012 16:59:41', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:59:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qxd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (650, '润滑计划单', 'equipoilingplansub.do?method=listPage', 'equipoilingplan', '润滑计划单', 1, 'admin', to_date('30-01-2012 17:01:43', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:01:43', 'dd-mm-yyyy hh24:mi:ss'), 0, 'rhjhd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (651, '维修计划单', 'equipRepairPlanSub.do?method=listPage', 'equiprepairplan', '维修计划单', 1, 'admin', to_date('30-01-2012 17:02:18', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:02:18', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wxjhd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (652, '蒸汽锅炉运行交接班记录', 'boilerrunhand.do?method=listPage', 'boilerrunhand', '蒸汽锅炉运行交接班记录', 1, 'admin', to_date('30-01-2012 17:02:25', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:02:25', 'dd-mm-yyyy hh24:mi:ss'), 1, 'zqglyxjjbjl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (654, '验收单', 'equipCheckingSub.do?method=listPage', 'equipchecking', '验收单', 1, 'admin', to_date('30-01-2012 17:07:06', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:07:06', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ysd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (662, '设备维修类别', 'equipRepairClass.do?method=listPage', 'equiprepairclass', '设备维修类别', 1, 'admin', to_date('30-01-2012 17:41:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:41:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sbwxlb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (663, '设备故障原因', 'equipStopPageCause.do?method=listPage', 'equipstoppagecause', '设备故障原因', 1, 'admin', to_date('30-01-2012 17:41:41', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:41:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sbgzyy');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (664, '设备故障类别', 'equipStoppageClass.do?method=listPage', 'equipStoppageClass', '设备故障类别', 1, 'admin', to_date('30-01-2012 17:42:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:42:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sbgzlb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (665, '设备检测类别', 'equipExamineClass.do?method=listPage', 'equipexamineclass', '设备检测类别', 1, 'admin', to_date('30-01-2012 17:49:47', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:49:47', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sbjclb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (44, '检验方案', 'qualityProgramSub.do?method=listPage', 'qualityprogram', '检验方案', 1, 'admin', to_date('08-07-2011 16:56:07', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-07-2011 16:56:07', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jyfa');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (82, '采购请购单', 'buyacquiresub.do?method=listPage', 'buyacquire', '采购请购单', 1, 'admin', to_date('18-07-2011 15:10:40', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('18-07-2011 15:34:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgqgd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (5, '物品信息', 'baseware.do?method=listPage', 'baseware', '物品信息', 1, 'admin', to_date('04-07-2011 13:32:52', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:32:52', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wpxx');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (7, '物品单位', 'baseWareUnit.do?method=listPage', 'basewareunit', '物品单位', 1, 'admin', to_date('04-07-2011 13:34:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:34:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wpdw');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (9, '基础计量单位', 'baseWareBaseUnit.do?method=listPage', 'basewarebaseunit', '基础计量单位', 1, 'admin', to_date('04-07-2011 13:35:48', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:35:48', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jcjldw');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (10, '基础计量单位与基础单位类别', 'baseWareBaseUnitAndUnit.do?method=listPage', 'basewarebaseunitclass', '基础计量单位与基础单位类别', 1, 'admin', to_date('04-07-2011 13:36:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:36:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jcjldwyjcdwlb');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (12, '操作员与权限', 'sysAuthorityData.do?method=listPage', 'sysauthoritydata', '操作员与权限', 1, 'admin', to_date('04-07-2011 13:37:34', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('04-07-2011 13:37:34', 'dd-mm-yyyy hh24:mi:ss'), 0, 'czyyqx');
commit;
prompt 200 records committed...
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (902, '科目设置', 'nfsubject.do?method=listPage', 'nfsubject', '科目设置', 1, 'admin', to_date('27-03-2012 11:13:17', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('10-04-2012 10:28:42', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kmsz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (903, '帐套', 'nfaccount.do?method=listPage', 'nfaccount', '帐套', 1, 'admin', to_date('27-03-2012 12:03:45', 'dd-mm-yyyy hh24:mi:ss'), 23, '财务', to_date('27-03-2012 12:08:03', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zt');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (904, '货币资料', 'nfcurrency.do?method=listPage', 'nfcurrency', '货币资料', 21, 'GHZ', to_date('27-03-2012 12:19:16', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-04-2012 16:38:43', 'dd-mm-yyyy hh24:mi:ss'), 0, 'hbzl');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (905, '付款单', 'nfpaymentsub.do?method=listPage', 'nfpayment', '付款单', 21, 'GHZ', to_date('27-03-2012 16:40:05', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('28-03-2012 09:38:14', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fkd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (921, '科目长度', 'nfsubjectsetup.do?method=listPage', 'nfsubjectsetup', '科目长度', 1, 'admin', to_date('28-03-2012 09:57:09', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-04-2012 15:26:46', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kmzd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (922, '会计项目', 'nfproject.do?method=listPage', 'nfproject', '会计项目', 1, 'admin', to_date('28-03-2012 13:59:40', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('28-03-2012 13:59:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'hjxm');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (923, '科目总账', 'nfGeneralLegerSubController.do?method=listPage', 'nfgeneralledger', '科目总账', 1, 'admin', to_date('28-03-2012 14:27:48', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('09-04-2012 09:59:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kmzz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (924, '结算方式', 'nfbalance.do?method=listPage', 'nfbalance', '结算方式', 1, 'admin', to_date('28-03-2012 15:05:31', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('28-03-2012 15:05:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jsfs');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (941, '收款单', 'nfproceeds.do?method=listPage', 'nfproceeds', '收款单', 21, 'GHZ', to_date('29-03-2012 10:55:23', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('29-03-2012 10:55:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'skd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (942, '出纳日记账', 'nfcashierdiary,do?method=listPage', 'nfcashierdiary', '出纳日记账', 1, 'admin', to_date('29-03-2012 12:23:25', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('29-03-2012 12:23:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cnrjz');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (944, '其他收入单', 'nfincomesub.do?method=listPage', 'nfincome', '其他收入单', 1, 'admin', to_date('29-03-2012 15:33:31', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('29-03-2012 15:33:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qtsrd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (945, '费用支出单', 'nfpaysub.do?method=listPage', 'nfpay', '费用支出单', 1, 'admin', to_date('29-03-2012 15:39:17', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('29-03-2012 15:39:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fyzcd');
insert into SYS_MODELWIN (id, c_name, c_url, c_imagename, c_memo, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (961, '支出项目', 'nfpayitem.do?method=listPage', 'nfpayitem', '支出项目', 21, 'GHZ', to_date('30-03-2012 15:41:04', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('30-03-2012 15:41:04', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zcxm');
commit;
prompt 213 records loaded
prompt Enabling triggers for SYS_MODELWIN...
alter table SYS_MODELWIN enable all triggers;
set feedback on
set define on
prompt Done.
