prompt PL/SQL Developer import file
prompt Created on 2012年5月1日 by Administrator
set feedback off
set define off
prompt Disabling triggers for SYS_CHECKTYPE...
alter table SYS_CHECKTYPE disable all triggers;
prompt Deleting SYS_CHECKTYPE...
delete from SYS_CHECKTYPE;
commit;
prompt Loading SYS_CHECKTYPE...
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (163, '生产预测单', 'PROD_FORECAST', 'PROD_FORECASTSUB', 'prodForecast.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('22-08-2011 13:32:18', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 13:33:03', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scycd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (8, '车间退料单', 'PROD_BACKWARE', 'PROD_BACKWARESUB', 'prodBackWare.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('24-08-2011 13:58:44', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('24-08-2011 15:18:13', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cjtld');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (32, '生产完工单', 'PROD_FINISHEDWARE', null, 'prodFinishedWare.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('25-08-2011 16:19:59', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('25-08-2011 16:19:59', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scwgd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (45, '生产加工单', 'PROD_WORKMAKE', null, 'prodWorkMake.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('26-08-2011 12:25:29', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('26-08-2011 12:25:29', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scjgd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (161, '生产指令', 'PROD_COMMAND', null, 'prodCommandController.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('22-08-2011 09:18:52', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 14:06:44', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (181, '调班记录', 'HUMAN_SWAP', null, 'humanswap.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('23-08-2011 09:24:05', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-08-2011 09:24:05', 'dd-mm-yyyy hh24:mi:ss'), 0, 'dbjl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (46, '班组领料', 'PROD_WORKWARE', null, 'prodWorkAcquireWareSubController.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('26-08-2011 13:17:26', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-09-2011 17:22:05', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bzll');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (282, '请假记录', 'HUMAN_LEAVE', null, 'humanleave.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('19-11-2011 14:29:19', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-11-2011 14:29:19', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qjjl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (283, '办公室发货指令', 'SELL_SENDWARECOMMANDOF', 'SELL_SENDWARECOMMANDOFSUB', 'sellsendwarecommandof.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('19-11-2011 14:31:37', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('28-11-2011 11:09:19', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bgsfhzl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (241, '供应商信息', 'BUY_CLIENT', null, 'buyClient.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('19-10-2011 13:02:21', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-10-2011 14:25:38', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gysxx');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (261, '主生产指令', 'PROD_MAINCOMMAND', 'PROD_MAINCOMMANDSUB', 'prodMainCommand.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('23-10-2011 22:49:46', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('20-03-2012 12:29:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zsczl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (182, '维修记录', 'HUMAN_REPAIR', null, 'humanrepair.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('23-08-2011 09:24:41', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-08-2011 09:24:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wxjl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (31, '生产派工单', 'PROD_STARTWORING', null, 'prodStartWorking.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('25-08-2011 13:48:52', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('25-08-2011 13:48:52', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scpgd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (221, '班组退料', 'PROD_WORKBACKWARE', null, 'prodWorkBackWareSubController.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('29-08-2011 10:02:35', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-09-2011 17:22:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bztl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (162, '替班记录', 'HUMAN_RELAY', null, 'humanrelay.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('22-08-2011 12:13:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 12:13:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'tbjl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (201, '班组交接单', 'PROD_WORKSWAP', 'PROD_WORKSWAPSUB', 'prodWorkSwap.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('28-08-2011 15:28:06', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('29-08-2011 16:35:22', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bzjjd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (4, '入库单', 'STOCK_INSTOCK', 'STOCK_INSTOCKSUB', 'stockInStock.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('26-07-2011 12:14:24', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 10:51:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'rkd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (5, '出库单', 'STOCK_OUTSTOCK', 'STOCK_OUTSTOCKSUB', 'stockoutstock.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('26-07-2011 12:14:38', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 10:44:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ckd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (113, '库存调拨单', 'STOCK_TRANSFER', 'STOCK_TRANSFERSUB', 'stockTransfer.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('27-07-2011 15:04:33', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 09:58:05', 'dd-mm-yyyy hh24:mi:ss'), 0, 'kcdbd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (1, '销售退货', 'SELL_BACKWARE', 'SELL_BACKWARESUB', 'sellbackware.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('06-07-2011 15:22:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:06:02', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsth');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (21, '采购请购单', 'BUY_ACQUIRE', 'BUY_ACQUIRESUB', 'buyacquire.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('19-07-2011 08:56:22', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-02-2012 14:45:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgqgd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (28, '请验单', 'QUALITY_FORWARDEXAMINE', 'QUALITY_FORWARDEXAMINESUB', 'qualityForwardExamine.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('19-07-2011 09:30:22', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('19-07-2011 09:30:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qyd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (24, '销售订单', 'SELL_SCHEDULE', 'SELL_SCHEDULESUB', 'sellSchedule.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('06-07-2011 10:22:27', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-07-2011 16:03:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsdd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (27, '销售运费', 'SELL_PORTAGE', 'SELL_PORTAGESUB', 'sellPortage.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('06-07-2011 11:55:10', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:06:36', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsyf');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (22, '销售发货指令', 'SELL_SENDWARECOMMAND', 'SELL_SENDWARECOMMANDSUB', 'sellsendwarecommand.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('06-07-2011 09:59:11', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 10:15:28', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsfhzl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (23, '销售发票申请', 'SELL_INVOICE', 'SELL_INVOICESUB', 'sellInvoice.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('06-07-2011 10:21:58', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 10:25:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'xsfpsq');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (25, '商品报价', 'SELL_QUOTEDPRICE', 'SELL_QUOTEDPRICESUB', 'sellQuotedPrice.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('06-07-2011 10:23:13', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('13-07-2011 14:17:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 'spbj');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (26, '年销售计划', 'SELL_PLAN', 'SELL_PLANSUB', 'sellPlan.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('06-07-2011 10:23:38', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-07-2011 14:17:37', 'dd-mm-yyyy hh24:mi:ss'), 0, 'nxsjh');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (42, '采购退货通知单', 'BUY_BACKWARENOTIFICATION', 'BUY_BACKWARENOTIFICATIONSUB', 'buybackwarenotification.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('21-07-2011 15:18:34', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('25-07-2011 12:51:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgthtzd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (61, '采购运费发票', 'BUY_PORTAGE', null, 'buyportage.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('22-07-2011 09:45:21', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-07-2011 12:07:55', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgyffp');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (2, '采购到货通知单', 'BUY_COMEWARENOTIFICATION', 'BUY_COMEWARENOTIFICATIONSUB', 'buyComeWareNotIfication.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('20-07-2011 14:20:43', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('11-08-2011 10:52:00', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgdhtzd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (121, '主生产计划', 'PROD_MPS', null, 'mPSSubController.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('12-08-2011 16:15:09', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-08-2011 13:54:37', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zscjh');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (141, '生产计划', 'PROD_SCHEDULE', null, 'prodPlanScheduleSubController.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('15-08-2011 14:15:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('15-08-2011 15:51:15', 'dd-mm-yyyy hh24:mi:ss'), 0, 'scjh');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (9, '车间领料单', 'PROD_ACQUIREWARE', null, 'prodAcquireWareSubController.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('24-08-2011 15:40:18', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-09-2011 17:24:58', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cjlld');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (302, '工作中心清场单', 'PROD_CLEARING', 'PROD_CLEARINGSUB', 'prodClearing.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 16:07:23', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 16:07:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzzxqcd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (304, '检测计划单', 'EQUIP_EXAMINEPLAN', 'EQUIP_EXAMINEPLANSUB', 'equipExaminePlan.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:14:51', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:14:51', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jcjhd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (305, '检测单', 'EQUIP_EXAMINE', 'EQUIP_EXAMINESUB', 'equipExamine.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:15:21', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:15:21', 'dd-mm-yyyy hh24:mi:ss'), 0, 'jcd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (306, '故障登记单', 'EQUIP_STOPPAGE', 'EQUIP_STOPPAGESUB', 'equipStopPage.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:15:55', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:15:55', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gzdjd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (309, '维修单', 'EQUIP_REPAIR', 'EQUIP_REPAIRSUB', 'equipRepair.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:17:33', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:17:33', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wxd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (310, '验收单', 'EQUIP_CHECKING', 'EQUIP_CHECKINGSUB', 'equipChecking.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:17:59', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:17:59', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ysd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (341, '保留样品档案', 'QUALITY_RETENTIONSAM', null, 'qualityRetentionSam.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('21-02-2012 13:45:43', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-02-2012 12:01:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'blypda');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (342, '制水检测单', 'PROD_WATERTEST', 'PROD_WATERTESTSUB', 'prodwatertest.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('21-02-2012 14:47:14', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-02-2012 13:42:33', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zsjcd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (361, '生产环境检测单', 'PROD_ENVIRONMENTTEST', 'PROD_ENVIRONMENTTESTSUB', 'prodenvironmenttest.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('22-02-2012 10:01:52', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-02-2012 10:01:52', 'dd-mm-yyyy hh24:mi:ss'), 0, 'schjjcd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (346, '润滑单', 'EQUIP_OILING', 'EQUIP_OILINGSUB', 'equipOiling.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('21-02-2012 17:34:38', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-02-2012 17:35:04', 'dd-mm-yyyy hh24:mi:ss'), 0, 'rhd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (401, '润滑计划单', 'EQUIP_OILINGPLAN', 'EQUIP_OILINGPLANSUB', 'equipOilingPlan.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('24-02-2012 16:23:57', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('12-03-2012 11:46:46', 'dd-mm-yyyy hh24:mi:ss'), 0, 'rhjhd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (363, '保留样品检测计划单', 'QUALITY_RETENTIONSAMPLAN', 'QUALITY_RETENTIONSAMPLANSUB', 'qualityretentionsamplanSub.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('22-02-2012 16:01:20', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('22-02-2012 16:01:56', 'dd-mm-yyyy hh24:mi:ss'), 0, 'blypjcjhd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (543, '付款单', 'NF_PAYMENT', 'NF_PAYMENTSUB', 'nfpayment.do?method=checkListPage' || '&' || 'ID=', 21, 'GHZ', to_date('30-03-2012 13:30:42', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('30-03-2012 13:54:00', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fkd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (561, '收款单', 'NF_PROCEEDS', 'NF_PROCEEDSSUB', 'nfproceeds.do?method=checkListPage' || '&' || 'ID=', 21, 'GHZ', to_date('31-03-2012 09:46:39', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('16-04-2012 10:47:18', 'dd-mm-yyyy hh24:mi:ss'), 0, 'skd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (621, '附属物品完工单', 'PROD_SUBSIDIARYWARE', null, 'prodsubsidiaryware.do?method=checkListPage' || '&' || 'ID=', 21, 'GHZ', to_date('13-04-2012 12:21:34', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('13-04-2012 12:21:34', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fswpwgd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (661, '公共费用申请', 'COMMON_MONEYUSE', null, 'commonmoneyuse.do?method=checkListPage' || '&' || 'ID=', 24, 'LGC', to_date('23-04-2012 12:10:43', 'dd-mm-yyyy hh24:mi:ss'), 24, 'LGC', to_date('23-04-2012 12:11:29', 'dd-mm-yyyy hh24:mi:ss'), 0, 'ggfysq');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (541, '其他收入单', 'NF_INCOME', 'NF_INCOMESUB', 'nfincome.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('30-03-2012 11:52:34', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-03-2012 11:52:34', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qtsrd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (542, '费用支出单', 'NF_PAY', 'NF_PAYSUB', 'nfpay.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-03-2012 11:53:53', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-03-2012 11:53:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fyzcd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (601, '录入凭证', 'NF_VOUCHER', 'NF_VOUCHERSUB', 'enterVoucher.do?method=enterPage' || '&' || 'ID=', 1, 'admin', to_date('05-04-2012 09:28:25', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('05-04-2012 09:28:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'lrpz');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (581, '银行存取款单', 'NF_BANKACCESS', null, 'nfbankaccess.do?method=checkListPage' || '&' || 'ID=', 21, 'GHZ', to_date('01-04-2012 15:42:16', 'dd-mm-yyyy hh24:mi:ss'), 21, 'GHZ', to_date('01-04-2012 15:42:16', 'dd-mm-yyyy hh24:mi:ss'), 0, 'yxcqkd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (421, '供应商预付款申请单', 'BUY_PAYAPPLY', null, 'buypayapply.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('06-03-2012 16:10:59', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('06-03-2012 16:10:59', 'dd-mm-yyyy hh24:mi:ss'), 0, 'gysyfksqd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (381, '保留样品检测单', 'QUALITY_RETENTIONSAMTEST', 'QUALITY_RETENTIONSAMTESTSUB', 'qualityretentionsamtestSub.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('23-02-2012 11:11:18', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('23-02-2012 11:11:44', 'dd-mm-yyyy hh24:mi:ss'), 0, 'blypjcd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (345, '保养单', 'EQUIP_KEEP', 'EQUIP_KEEPSUB', 'equipkeep.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('21-02-2012 17:32:25', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-02-2012 17:33:33', 'dd-mm-yyyy hh24:mi:ss'), 0, 'byd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (442, '生产再利用回收单', 'PROD_REUSEWARE', 'PROD_REUSEWARESUB', 'prodreusewaresub.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('08-03-2012 11:57:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-03-2012 11:58:08', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlyhsd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (462, '返工领料单', 'PROD_REVERSEACQUIREWARE', 'PROD_REVERSEACQUIREWARESUB', 'prodreverseacquireware.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('09-03-2012 11:31:51', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('20-03-2012 15:07:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fglld');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (41, '质检单', 'QUALITY_EXAMINE', 'QUALITY_EXAMINESUB', 'qualityExamine.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('21-07-2011 14:07:35', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-07-2011 14:07:35', 'dd-mm-yyyy hh24:mi:ss'), 0, 'zjd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (503, '返工完工单', 'PROD_REVERSEFINISHEDWARE', null, 'prodreversefinishedware.do?method=checkListPage' || '&' || 'ID=', 3, '王利', to_date('13-03-2012 14:14:03', 'dd-mm-yyyy hh24:mi:ss'), 3, '王利', to_date('13-03-2012 14:14:03', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fgwgd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (482, '有资质供应商', 'BUY_CLIENT', null, 'buyClient.do?method=checkListPage' || '&' || 'ID=', 4, 'ghz', to_date('12-03-2012 15:32:04', 'dd-mm-yyyy hh24:mi:ss'), 4, 'ghz', to_date('12-03-2012 15:32:04', 'dd-mm-yyyy hh24:mi:ss'), 0, 'yzzgys');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (443, '生产再利用生产指令', 'PROD_REUSECOMMAND', null, 'prodreusecommand.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('08-03-2012 11:58:40', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-03-2012 11:58:52', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlysczl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (422, '返工生产指令', 'PROD_REVERSECOMMAND', null, 'prodreversecommand.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('07-03-2012 16:52:31', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('07-03-2012 16:52:31', 'dd-mm-yyyy hh24:mi:ss'), 0, 'fgsczl');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (444, '生产再利用领料单', 'PROD_REUSEACQUIREWARE', 'PROD_REUSEACQUIREWARESUB', 'prodreuseacquirewaresub.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('08-03-2012 13:59:44', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('08-03-2012 14:00:26', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlylld');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (463, '生产再利用完工单', 'PROD_REUSEFINISHEDWARE', null, 'prodreusefinishedware.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('09-03-2012 13:45:09', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('09-03-2012 13:53:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'sczlywgd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (29, '采购订单', 'BUY_SCHEDULE', 'BUY_SCHEDULESUB', 'buySchedule.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('19-07-2011 13:48:34', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('21-07-2011 12:17:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'cgdd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (301, '不合格物品入库单', 'STOCK_FAILEDWARE', 'STOCK_FAILEDWARESUB', 'stockFailedWare.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 15:43:22', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('01-03-2012 16:46:45', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bhgwprkd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (303, '保养计划单', 'EQUIP_KEEPPLAN', 'EQUIP_KEEPPLANSUB', 'equipKeepPlan.do?method=checkingPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:07:37', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:07:37', 'dd-mm-yyyy hh24:mi:ss'), 0, 'byjhd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (307, '请修单', 'EQUIP_REQUEST', 'EQUIP_REQUESTSUB', 'equipRequest.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:16:39', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:16:39', 'dd-mm-yyyy hh24:mi:ss'), 0, 'qxd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (308, '维修计划单', 'EQUIP_REPAIRPLAN', 'EQUIP_REPAIRPLANSUB', 'equipRepairPlan.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:17:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:17:08', 'dd-mm-yyyy hh24:mi:ss'), 0, 'wxjhd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (311, '安装单', 'EQUIP_SETUP', 'EQUIP_SETUPSUB', 'equipSetup.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:18:28', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:18:28', 'dd-mm-yyyy hh24:mi:ss'), 0, 'azd');
insert into SYS_CHECKTYPE (id, c_name, c_maintablename, c_childtablename, c_actionurl, i_oper_id, c_oper_name, d_insert_date, i_oper_modifyid, c_oper_modifyname, d_modify_date, i_del, c_aliascode)
values (312, '变更单', 'EQUIP_CHANGE', 'EQUIP_CHANGESUB', 'equipChange.do?method=checkListPage' || '&' || 'ID=', 1, 'admin', to_date('30-01-2012 17:18:51', 'dd-mm-yyyy hh24:mi:ss'), 1, 'admin', to_date('30-01-2012 17:18:51', 'dd-mm-yyyy hh24:mi:ss'), 0, 'bgd');
commit;
prompt 73 records loaded
prompt Enabling triggers for SYS_CHECKTYPE...
alter table SYS_CHECKTYPE enable all triggers;
set feedback on
set define on
prompt Done.
