@wrap iname=.\fun\FUN_PRODAUTOLINECENTERCSS.sql oname=.\out\FUN_PRODAUTOLINECENTERCSS.plb 
@wrap iname=.\fun\FUN_PRODCENTERNEXTMAKE.sql oname=.\out\FUN_PRODCENTERNEXTMAKE.plb 
@wrap iname=.\fun\FUN_PRODCENTERNEXTSEQUENCE.sql oname=.\out\FUN_PRODCENTERNEXTSEQUENCE.plb 
@wrap iname=.\fun\FUN_PRODCRAFTSEQUENCE_MAKETIME.sql oname=.\out\FUN_PRODCRAFTSEQUENCE_MAKETIME.plb 
@wrap iname=.\fun\FUN_PRODWORKCENTERSTATUS.sql oname=.\out\FUN_PRODWORKCENTERSTATUS.plb 
@wrap iname=.\fun\FUN_PRODWORKCENTERSTATUSSUB.sql oname=.\out\FUN_PRODWORKCENTERSTATUSSUB.plb 
@wrap iname=.\fun\FUN_READNEXTCOMMAND.sql oname=.\out\FUN_READNEXTCOMMAND.plb 
@wrap iname=.\fun\PROCE_GENERATE_CENTER_SEQUENCE.sql oname=.\out\PROCE_GENERATE_CENTER_SEQUENCE.plb 



